version: '3'

services:
  api:
    build: 
      context: ./
      dockerfile: dev.Dockerfile
    # second port is container's port
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./dev-db.env
      - ./dev.env

  frontend:
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/src/app
      - /frontend/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true

  database:
    image: postgres
    env_file:
      - ./dev-db.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

